version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"  # Expose Next.js frontend on port 3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"  # Expose Express backend on port 5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
